name: cross compile x86

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cross-x86:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake gcc-multilib
    
    - name: extract and build cake compiler
      run: |
        tar -xzf cake-unverified-x64-64.tar.gz
        cd cake-unverified-x64-64
        make cake
        sudo cp cake /usr/local/bin/cake
        cd ..
    
    - name: create x86 toolchain file
      run: |
        cat > x86_64-linux-gnu.cmake << 'EOF'
        set(CMAKE_SYSTEM_NAME Linux)
        set(CMAKE_SYSTEM_PROCESSOR x86_64)
        
        set(CMAKE_C_COMPILER gcc)
        
        set(CMAKE_C_FLAGS "-m64")
        
        set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
        set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
        set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
        EOF
      
    - name: configure cmake for x86 cross compile
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=../x86_64-linux-gnu.cmake ..
    
    - name: build c version for x86
      run: |
        cd build
        make mibench-dijkstra-c
    
    - name: build pancake version for x86
      run: |
        cd build
        make mibench-dijkstra-pancake
    
    - name: verify x86 binaries and test execution
      run: |
        cd build/bin/mibench-dijkstra
        file mibench-dijkstra-c mibench-dijkstra-pancake
        echo "testing c version execution:"
        timeout 10 ./mibench-dijkstra-c input.dat > /dev/null
        echo "testing pancake version execution:"
        timeout 10 ./mibench-dijkstra-pancake input.dat > /dev/null
        echo -e "\033[32msuccess: x86 cross compilation and execution completed\033[0m"